source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Calendar_Example' do
  pod 'Calendar', :path => '../'
end

target 'Calendar_Tests'  do
  pod 'Calendar', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
