# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
script:
  - xctool test -workspace Example/Calendar.xcworkspace -scheme Calendar-Example -sdk iphonesimulator -destination "name=iPhone 6"
