# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
script:
  set -o pipefail
  xcodebuild test  -workspace Calendar.xcworkspace -sdk iphonesimulator -scheme Calendar -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6" build test  | xcpretty -c  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Calendar'
